version: '3.4'

services:
  nodebackend:
    image: nodebackend
    build:
      context: node
      dockerfile: ./Dockerfile
    environment:
        NODE_ENV: production
        CONNECTION: ${CONNECTION}
        JWT_SECRET: ${JWT_SECRET}
        EMAIL_USER: ${EMAIL_USER}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        PORT: ${PORT}
    ports:
      - 4000:4000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
